#!/bin/sh

export NODE_PATH=`pwd`
export NODE_ENV=prod

while [[ true ]]
do
    node server.js &
    SERVER_PID=$!
    inotifywait --excludei .swp -e modify server.js src/ public/ views/ games/
    kill -15 $SERVER_PID
done
